### ISSUE TITLE
Compability with wordpress install option

### ISSUE THREAD

**Issue by oZeca** [daverogers/serverpilot-php#4]
Hey.

Want to add **wordpress install option** to your script?
Realy easy:

`
	public function app_create( $name, $sysuserid, $runtime, $domains = array(), $wordpress = array() ) {
		$params = array(
			"name"		=> $name,
			"sysuserid"	=> $sysuserid,
			"runtime"	=> $runtime);
		if( $domains ){
			$params["domains"] = $domains;
		}

		$params["wordpress"] = $wordpress;

		return $this->_send_request( "apps", $params, ServerPilot::SP_HTTP_METHOD_POST );
	}
`

**Usage:**
`$sp->app_create('name', 'user', 'runtime', ['domains'], ["site_title"=>"site name", "admin_user"=>"admin", "admin_password"=>"your_password", "admin_email"=>"admin@xyz.come"] );`

That's is!

**Comment by timgavin** [comment]
Excellent, thanks! :)

**Comment by oZeca** [comment]
:)

**Comment by bigwilliam** [comment]
Have you had any luck getting this to install WP? I have not. It installs an "app" but seems to disregard setting up WP.

**Comment by timgavin** [comment]
@bigwilliam  I had to tweak it just a bit but got it to work using the following.

#### form.php
```
<input type="checkbox" name="wordpress" id="wordpress" value="wordpress"> This is a Wordpress site
```

#### ServerPilot.php
```
public function app_create($name, $sysuserid, $runtime, $domains = [], $wordpress = []) {
	$params = array(
		'name' => $name,
		'sysuserid' => $sysuserid,
		'runtime' => $runtime);
	if($domains)
		$params['domains'] = $domains;
    
    if(!empty($wordpress)) {
        $params['wordpress'] = $wordpress;
    }

	return $this->_send_request('apps', $params, ServerPilot::SP_HTTP_METHOD_POST);
}
```

#### usage
```
if(isset($_POST['wordpress']))
{
	$wordpress = [
		'site_title' => $_POST['site_title'],
		'admin_user' => $_POST['sftpusername'],
		'admin_password' => $_POST['sftppassword'],
		'admin_email' => $_POST['admin_email']
	];

	$sp->app_create(strtolower($_POST['appname']), $user, $_POST['phpversion'], [$_POST['appdomain'], 'www.'.$_POST['appdomain']], $wordpress);

} else {
	$sp->app_create(strtolower($_POST['appname']), $user, $_POST['phpversion'], [$_POST['appdomain'], 'www.'.$_POST['appdomain']]);
}
```

**Comment by bigwilliam** [comment]
The issue was the site title parameter. I was using "title" instead of "site_title" - but I was referring to the Readme Screenshot: http://d3fy.xyz/1gT9r
